### ISSUE TITLE
failed building web

### ISSUE THREAD

**Issue by chriskisskiss** [secure-77/Perlite#103]
hi,

using the original docker-compose, I get this Error:
```
Building web
[+] Building 0.2s (2/2) FINISHED                                      docker:default
 => [internal] load build definition from Dockerfile                            0.0s
 => => transferring dockerfile: 2B                                              0.0s
 => [internal] load .dockerignore                                               0.1s
 => => transferring context: 2B                                                 0.0s
ERROR: failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount792667775/Dockerfile: no such file or directory
ERROR: Service 'web' failed to build : Build failed
```
perlite without the webserver is building fine. Any ideas?
Running on newest ubuntu.

Thank you

**Comment by secure-77** [comment]
You need to git clone the repo, make sure there is the sub folder web with the Dockerfile available

**Comment by yunghope** [comment]
I also have this problem and also have the subfolder web with the Dockerfile but I still have the problem

**Comment by secure-77** [comment]
what is your error message?

**Comment by yunghope** [comment]
> what is your error message?

Building web
[+] Building 0.2s (2/2) FINISHED                                      docker:default
 => [internal] load build definition from Dockerfile                            0.0s
 => => transferring dockerfile: 2B                                              0.0s
 => [internal] load .dockerignore                                               0.1s
 => => transferring context: 2B                                                 0.0s
ERROR: failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount792667775/Dockerfile: no such file or directory
ERROR: Service 'web' failed to build : Build failed

**Comment by secure-77** [comment]
Really not sure whats the problem. Tested this on a fresh vm

```bash
git clone https://github.com/secure-77/Perlite 
cd Perlite
sudo docker compose -f docker-compose.yml up
```

![image](https://github.com/secure-77/Perlite/assets/31564517/31bd1bad-7f4a-41b7-87fd-9b2fe8015386)

**Comment by yunghope** [comment]
ok it's work now but how can I edit on perlite now? I cant understand

**Comment by secure-77** [comment]
What you mean with "edit" ? 
You can just replace the "Demo" folder with your Vault folder

![image](https://github.com/secure-77/Perlite/assets/31564517/b8f2840d-62f9-4efe-b191-5ea13db7cda0)

and adjust the vault name in the docker `docker-compose.yml`

![image](https://github.com/secure-77/Perlite/assets/31564517/205ad628-6543-4f98-89dd-305196ce5ba1)

**Comment by secure-77** [comment]
ok, then look at my comment and also read the wiki: https://github.com/secure-77/Perlite/wiki
