### ISSUE TITLE
PDF and MP4 files rendering with WIKILinks

### ISSUE THREAD

**Issue by SenPoo** [secure-77/Perlite#105]
Perlite is a great project, and it is the best way for me to publish my Obsidian vault. I wonder if it is possible to add support for rendering embedded PDF and MP4 files on a webpage using the wikilinks "![[xxxx]]". 

I have already tried using HTML syntax such as `<video>` or `<embed>` in a markdown file, and it worked for rendering the PDF and MP4 files with the absolute path.

But the relative path resolution is a little bit difficult due to different root directories between the index.html and Obsidian vault, I guess. I think it will be really useful and convenient if adding the direct rendering support.

Thanks and best wishes.

**Comment by secure-77** [comment]
fixed / implemented in 1.5.8

**Comment by shawnpoo** [comment]
> fixed / implemented in 1.5.8

Nice, appreciate!
