### ISSUE TITLE
YAML frontmatter not displayed

### ISSUE THREAD

**Issue by crendl** [secure-77/Perlite#107]
**Describe the bug**
Currently, yaml frontmatter is not displayed. 

**To Reproduce**
e.g., `markdown-sample3.md` from the demo include yaml, which is not visible
https://perlite.secure77.de/?link=%2FDemo%20Documents%2Fmarkdown-sample3

**Expected behavior**
display of yaml metadata in perlite.

**Comment by secure-77** [comment]
its fixed on the dev branch and will be included in the next release

**Comment by secure-77** [comment]
fixed / implemented in 1.5.8
