### ISSUE TITLE
Feature request: Dataview

### ISSUE THREAD

**Issue by fugohan** [secure-77/Perlite#108]
**Is your feature request related to a problem? Please describe.**
I would like to use the Obsidian Dataview Pluginwith perlite. I use it to track my study process and to get an overview how much I need to learn/exercise. To have this ability via perlite would be awesome because my colleagues could check my progress. 

**Describe the solution you'd like**

I saw a project called [publishkit](https://github.com/publishkit/sdk-source) who has implemented this function but I don't know how. 

**Additional context**

Maybe I linked the wrong repo. In the Organisation are more repos.

**Comment by secure-77** [comment]
Sry but for the moment I won`t support or implement plugins, its to much effort to track changes of them. If you want to have this in Perlite you need to implement this by your self or find someone who will do it.
