### ISSUE TITLE
Support for random note?

### ISSUE THREAD

**Issue by xjtu-blacksmith** [secure-77/Perlite#109]
**Is your feature request related to a problem? Please describe.**
The [random note](https://help.obsidian.md/Plugins/Random+note) core plugin is somewhat useful for the Zettelkasten users like me. Sometimes I need to review my notes on my cell phone, and I do not want to sync the files to there to use Obsidian, when Perlite should be much better. If Perlite has random note feature, the review process could be carry out easier.

And I personally think it is not difficult to implement this function with helps of the metadata file, just like the Graph feature of Perlite.

**Describe the solution you'd like**
Add a button (a dice as symbol) for skipping to random notes in the sidebar of Perlite's page (below the global Graph button), just like that in Obsidian. When user clicks the button, Perlite will lead user to a random page that exists in the vault.

**Describe alternatives you've considered**
This feature is not necessary for many users, so maybe it can be turned on and off (or simply keep off by default) by env variables.

**Additional context**
The skipping target can simply be extracted from the metadata file used by Graph, which may be the quickest way (rather than going over the directory).

**Comment by secure-77** [comment]
its fixed on the dev branch and will be included in the next release. Please note that this feature will require a working graph.

**Comment by xjtu-blacksmith** [comment]
Thanks for your great work! I'll try that in the next version.

**Comment by secure-77** [comment]
fixed / implemented in 1.5.8
