### ISSUE TITLE
embed link

### ISSUE THREAD

**Issue by jeffreydong** [secure-77/Perlite#110]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Embed another file like `![[Plugins makes Obsidian special for you]]`

**Describe alternatives you've considered**

**Additional context**

**Comment by secure-77** [comment]
hey, this will not be implemented at the moment, however you can enable the mouse hover function in perlite to get a preview of the file, you need to enable the pop hover function in the settings

![image](https://github.com/user-attachments/assets/8020342c-29cd-4424-b43a-eefb48a1ca3c)

![image](https://github.com/user-attachments/assets/08dde6f8-502e-46d2-b16b-9d4f824886e0)
