### ISSUE TITLE
Minimizing callouts doesn't work

### ISSUE THREAD

**Issue by Yaro2709** [secure-77/Perlite#113]
Minimizing callouts doesn't work. Screenshot attached:
![test](https://github.com/secure-77/Perlite/assets/51800453/111a5f60-1ff6-4e03-bd55-3e2874ec1782)
code:
```md
> [!note]+ Information the user should notice even if skimming. 
> Test
```

**Comment by secure-77** [comment]
its fixed on the dev branch and will be included in the next release
