### ISSUE TITLE
Add config option to always show sidebar on mobile

### ISSUE THREAD

**Issue by russell-phillips** [secure-77/Perlite#120]
**Is your feature request related to a problem? Please describe.**
The sidebar (with the icon to show/hide the navigation pane, graph view button, and random note button) is always visible on desktop, but not on mobile.

I find it's not obvious how to make the sidebar visible, and I get complaints from users.

**Describe the solution you'd like**
I'd like a config option to have the sidebar always visible, including on mobile.

**Describe alternatives you've considered**
I'd be happy for the sidebar to be always visible, without any way to turn it off :-) But I assume some users would like to be able to retain the current behaviour, so a config option is probably better.

**Comment by secure-77** [comment]
I think its ok to always display the side bar on mobile, I removed the corresponding javascript function

**Comment by secure-77** [comment]
implemented in release [1.5.9](https://github.com/secure-77/Perlite/releases/tag/1.5.9)
