### ISSUE TITLE
Does Perlite support XAMPP

### ISSUE THREAD

**Issue by jimmy123j** [secure-77/Perlite#124]
I use the XAMPP and follow non-docker setup step, but can't find the www.conf file to start

does Perlite support XAMPP setting or someone can share the setup step with XAMPP will be appreciated

thanks !!

**Comment by secure-77** [comment]
Never tried it on windows but if you have XAMPP with PHP running you can easy test it. But maybe some things (probably path related) won't work. The graph for example uses the /tmp directory on linux to store the pre-calculated path, this won't work on windows without adjustments

**Comment by jimmy123j** [comment]
I think, XAMPP probability workable even not 100% support
but I don't know how to start to setup actually, 'casue XAMPP PHP path not same as original PHP setting

**Comment by jimmy123j** [comment]
> Still not sure on which point you are at the moment, do you get PHP already running (without Perlite)?

Yes, apache, PHP and Web all working
 I just don't know how to start setup the Perlite on XAMPP env's PHP, 'cause without setup document can be referenced

**Comment by secure-77** [comment]
No idea how to define php environment variables in xampp but you can just download the latest release and put the perlite folder ind your htdocs (or whatever) web root directory and check if the demo works
