### ISSUE TITLE
Some links are breaking the page for no apparent reason

### ISSUE THREAD

**Issue by codergoblin** [secure-77/Perlite#128]
I have many instances in my wiki where links break the page in a strange way.  

![image](https://github.com/secure-77/Perlite/assets/72735596/943a4b51-14c9-4efa-81cb-f4e22dca383e)

```
root@vultr:/opt/Perlite# cat /data/perlite/Sif/Kugelglobe.md 

A strange cubic object that irradiates light.
Found by [[Triya]] on a beach in [[Synthea]]. LPH later discovered that the globe was probably from [[Phanes]] since it fits perfectly in an artifact stand that the party found in an underground [[Antediluvians]] ossuary underneath [[Sif]]. LPH got a confirmation of this theory when the [[Antediluvians]] ([[Stargazers]]) that [[Triya]] faced in the [[Temple of Bes]] performed the same type of magic that [[Triya]] does. 
```

it looks like in this case ` [[Triya]]` breaks the link, but not sure why, it does not seem to be any different to other links that function correctly. It happens in different pages with different links but I can't see any pattern.

**Comment by rgaricano** [comment]
Yes, it happend to me too,
It happend if the name of the link have some image extension on it, as tif gif tiff bmp ....
I solved changing regexpression of line 161 of perlite/content.php as follow:
	$pattern = array('/(\!?\[\[)(.*?)(.png|.jpg|.jpeg|.svg|.gif|.bmp|.tif|.tiff)\|?(.+\|)(\]\])/');
(it's noted under //img link with captions replace block )
and restart server:
 systemctl restart php8.3-fpm nginx

**Comment by secure-77** [comment]
fixed in release [1.5.9](https://github.com/secure-77/Perlite/releases/tag/1.5.9)

**Comment by rgaricano** [comment]
thx,
I hope in a future propose changes through pull requests.

**Comment by secure-77** [comment]
of course, Im always open to PRs! thanks for your contribution!
