### ISSUE TITLE
Dead Link in Wiki for "01 Setup (No Docker)"

### ISSUE THREAD

**Issue by abdulharb** [secure-77/Perlite#129]
Hi team,

I've been trying to set up Perlite and ran into an issue with a dead link in the wiki for "01 Setup (No Docker)". The link to the nihilism guide is no longer active. However, I found the updated link through a Google search:

[Updated Link to Nihilism Guide](https://blog.nihilism.network/selfhosting/perlite/index.html)

Could you please update the wiki with this new link?

Thanks for your help!

Thanks,
Abdul!

**Comment by secure-77** [comment]
Thx, its updated
