### ISSUE TITLE
Docker hub

### ISSUE THREAD

**Issue by Mylloon** [secure-77/Perlite#14]
**Is your feature request related to a problem? Please describe.**
Not available without building it yourself, it would simplify the deployment without this extra-step!

**Describe the solution you'd like**
Being available without the need of building it.

**Describe alternatives you've considered**
Docker Hub and the github packages "ghcr.io" are available for free.

**Comment by secure-77** [comment]
Hey,

I will have a look at it, but this has no Prio at the moment for me so this could take some time to get be done.

BR,
sec77

**Comment by secure-77** [comment]
@Mylloon I created a docker hub account and added the  `sec77/perlite:latest`  image to the repo https://hub.docker.com/r/sec77/perlite

At the moment I don`t want to setup an auto push / build pipeline for every commit, I will build and push a new docker image for every release and not commit (scripted based or manually), but thanks nerveless for your effort! 

BR,
sec77
