### ISSUE TITLE
Excluding subfolders

### ISSUE THREAD

**Issue by pyjoku** [secure-77/Perlite#143]
Hi I am using perlite on my webhosting. So I have to edit the helper.php with my own variables.

I am trying to exclude a subfolder. 

$hideFolders = "Atlas,Calendar";

So far this works. But I cannot exclude subfolder or folders with space in its name.

Is it not possible? Or am I doing something wrong?

**Comment by secure-77** [comment]
Hi,
maybe the split of the array is not working correct when the folder name has a space in it. I will take a look and let you know.

**Comment by pyjoku** [comment]
Hi, I have been testing this again.
I found out out that the problem is the path is not checked.
My expectation was that I would definde the absolute path from the perlite directory, in fact it is just a single folder name without the path that is being excluded. Also every other folder with the exact same name is also hidden.

So when I have "calendar/2023" and want to exclude the year 2023-folder this is done by setting the $hidefolders with just 2023 and not the path of the folder. But it results in all 2023 folders being hidden no matter where they are located within the vault.

I think the code should reflect the option to exclude an absolute path.

**Comment by pyjoku** [comment]
I wanted to have both options available in the code, so excluding folder names as well as excluding a specific path.
I changed the code. I am no programmer so this was a bit trial and error

**I expanded the variables and use them as array**

// hide folders
// $hideFolders = getenv('HIDE_FOLDERS');
$hideAbsPath = array("+" ,"Calendar/2023","BMO/Profiles","x","Atlas/Dots/People");
$hideFoldername = array("My");
$hideFolders = array_merge($hideAbsPath);

**I removed this function as the variables above a no strings anymore**
// hide folders
//if (strcmp($hideFolders, '')) {
//	$hideFolders = explode(',', $hideFolders);
//} else {
//	$hideFolders = array();
//}

**Lastly I changed this function**

function isValidFolder($file)
{

	global $hideFolders;
	global $hideAbsPath;
	global $hideFoldername;

	// I want the full path
	// getFolderInfos() would be the better choice for this
	// mb_basename() changed
	$folderName = getFolderInfos($file)[0]; // absolute path
	$folderWildcard = getFolderInfos($file)[2]; // folder name as wildcard
	
	// check if folder is in array
		// absolute path to be excluded
	if (in_array($folderName, $hideAbsPath, true)) {
		return false;
	}
		// foldername to be excluded
	if (in_array($folderWildcard, $hideFoldername, true)) {
		return false;
	} 
	if (strcmp(substr($folderName, 0, 1), '.') !== 0) {
		return true;
	}

	return false;
}

---
With the code change above I can exclude folder names or specific path from ym vault. This is done on a shared webhoster hostpoint.ch

Since I don't know where those variables had to be changed I altered the helper.php directly.
