### ISSUE TITLE
Fix crucial Unsupported Plugins compatibility 

### ISSUE THREAD

**Issue by Selviniahh** [secure-77/Perlite#145]
I am using two important plugins that are not working when hosted with Perlite:

    Style Settings: I've configured my theme with this plugin, but its settings aren't persistent with Perlite.
    Shiki Highlighter: This plugin colors code snippets based on the language, but it is also unsupported.

I've shared a link to my vault containing a single note. Could you open this vault locally to see how these plugins are applied in my theme and find a way to make them compatible with Perlite?

https://drive.google.com/file/d/1l-OIt7KoSMWIq4PhRG6_wKpNncag-db5/view?usp=sharing

**Comment by secure-77** [comment]
Sorry, but I cant support plugins, there are way to many and they are also changing, so no way for me to support them. If you need them, you need to implement this by yourself.
