### ISSUE TITLE
Support Callouts

### ISSUE THREAD

**Issue by Tooa** [secure-77/Perlite#20]
Hi :wave:, 

one of the recent Obsidian releases introduced `callouts`. I use them a lot in my vaults and I would really love to see them supported in Perlite. I don't think the first implementation has to be too fancy. Rendering all different callout types (`WARNING`, `INFO`, etc.) the same way is fine for my use case.

Right know, defining a callout in Obsidian as follows:

```md
> [!WARNING] A Title
> Contents
```

renders as  (tested on c757c66bab483bb12e7edfb1d3091d01fa3afee0)

![image](https://user-images.githubusercontent.com/5375334/175761822-a41e0c16-2202-464f-8899-1c7c4e7e7a0b.png)

## Proposals

I don't think that `parsedown` supports callouts as it seems like a custom thing - especially the syntax. Maybe we can render them a different way then?

### Render as Block-quotes

![image](https://user-images.githubusercontent.com/5375334/175762698-5e7d42be-3897-4b32-b26d-d43376381504.png)

This [example](https://parsedown.org/tests/compound_blockquote) shows that this should actually work already.

### Render as Markdown

![image](https://user-images.githubusercontent.com/5375334/175762812-d2259981-2fb9-4f7d-a987-aa096d9a6cdc.png)

## Notes

I would like to express my gratitude to you. Perlite works really well and the Docker deployment helps a lot to spin it up in zero time.

**Comment by secure-77** [comment]
Hey @Tooa 👋 

This should be simple by adjusting the css, in the lastest commit I already added some margin for the blockquote tag. If it breaks nothing else I think I can also take about the headline and can add some css classes for the different types. 

I will see that I can add this in the next release.

BR,
Sec77

**Comment by Tooa** [comment]
Sounds great. I took a lead on this and improved the block-quote style in #25 

![image](https://user-images.githubusercontent.com/5375334/176133383-92ddaef3-d42f-41f5-b704-b6c6e39672d0.png)

Next, we could add enhancements for the different Callout styles. Do you have a good idea how we can assign different CSS classes based on the type? At the moment we can just identify that it is a block-quote element.

**Comment by secure-77** [comment]
this is implemented by @Tooa 🥳 in version 1.4.4
