### ISSUE TITLE
Add outline for documents

### ISSUE THREAD

**Issue by Tooa** [secure-77/Perlite#21]
Hi :wave:,

I would like to see an outline per page added to Perlite. The outline can be rendered on the right side of each document. One could switch via a button between displaying the graph or the outline.

Let me know what you think about it. Thanks for considering this enhancement.

**Comment by secure-77** [comment]
Hi @Tooa,

Nice idea but this seems to be more work, theoretical this should be possible via JS. But there are some layout adjustments also necessary.

Can´t promise if Iam going to implement this at the moment but feel free to create a pull request.

BR,
Sec77

**Comment by hellrazorx64** [comment]
Hi
 it could be a nice addition.
I really like the current ''webbed'' view on the right too, it basically all you ask for to have a quick view of where the document is heading to or to what it's connected to. It gives PURPOSE to that messy non sense Obisidan shows by default.

II was thinking, while not minimizing the complexity of that new feature (outliner), could be toggled between the two view with a button:

- Current web view (webbed view links)
- Outine

That could help, at least, having to rethink elements placement.
Just my two cents about the topic.

**Comment by secure-77** [comment]
Outline is added in https://github.com/secure-77/Perlite/commit/68b05cb4621d054fdc6c3a2f8f9bdfe3fd6ca054

![image](https://user-images.githubusercontent.com/31564517/197875951-ae462779-d674-4c34-9287-155e42e61874.png)

**Comment by hellrazorx64** [comment]
This is more better than bestest best.
