### ISSUE TITLE
Images reference breaks Obsidian to Google drive To dataset to perlite

### ISSUE THREAD

**Issue by hellrazorx64** [secure-77/Perlite#29]
Obsidian Vault is mapped to a google drive.
Cloud sync periodically pulls data off the cloud to a Truenas dataset
Data set is shared to perlite server with NFS share

Tested with document pwndbg.md (from demo folder):
Copied whole folder Dynamic Analyses to the Google drive

Images are rendered to Perlite.
MD referenced are mapped to (for example)

![[docs/Pasted image 20211031200413.png]] in the original MD file

IF Obsidian touches the document, is changes the image reference to:
![[Pasted image 20211031200413.png]]

Then it breaks on perlite
![image](https://user-images.githubusercontent.com/82125317/176942413-f27e52d7-2822-49d5-9269-cedb4eb2e0e4.png)

I tried adding the /docs/ before the image name like in the original file:
Images reference breaks in obsidian but works on perlite.

I the tried ./docs/ And it Works...

Is there a special trick to make this work more fluently? Plugin that should be used? From my perspective, my Obsidian version does not work as indended with image references.

Thanks

**Comment by secure-77** [comment]
He @hellrazorx64,

In the options `Files & Links` you need to set the New link format to `Relative path to file`

BR
Sec77

**Comment by hellrazorx64** [comment]
You are awesome! thank you!
