### ISSUE TITLE
Wildcard for exclusion

### ISSUE THREAD

**Issue by hellrazorx64** [secure-77/Perlite#30]
Is it possible to hide files and folders containing a particular character in the Compose file.
(or anywhere else)

I tried       - HIDE_FOLDERS=docs,private,trash,-*
for example, of course it didn't work.

The aim of doing this is being able to hide **folders** off the Perlite View, while still making the files freely available in Obsidian.

function isValidFolder($file)
{

	global $hideFolders;
	$folderName = mb_basename($file);

	// check if folder is in array
	if (in_array($folderName, $hideFolders, true)) {
		return false;
	}

	**if (strcmp(substr($folderName, 0, 1), '.') !== 0) {**
		return true;
	}

	return false;
}

I expect I could add somthing around that '.' in there, but I really don't know what i'm doing!

Thanks for your help

**Comment by secure-77** [comment]
Hey,

What exactly do you want to archive? Do you want to hide folders that start with a `-` or include a dash at any position of the folder name?

if you just want to check the beginning of the folder you can adjust this function to something like that. 

```php
if (strcmp(substr($folderName, 0, 1), '-') !== 0) {
	return true;
}
```
folder and files beginning with a `.` will be still excluded by the default php glob behavior, so the original function here is a little bit useless but works perfect as  a template.

**Comment by hellrazorx64** [comment]
Exactly. That will work for me.
A given character at the begining of the folder is fine.
