### ISSUE TITLE
Headers Hyperlink inside a Document

### ISSUE THREAD

**Issue by hellrazorx64** [secure-77/Perlite#32]
Obsidian Supports references toward Headings inside a document:

[[Document#Heading1]]

Which is use full for large markdown documents.

These Links seems to break in Perlite, showing empty pages.

Note: This feature is competing with outline view of documents.

**Comment by athshean** [comment]
Can confirm this issue. Any links with a tag reference breaks.

**Comment by secure-77** [comment]
Yes, this comes from the `#tag ` implementation, need to check if I can fix this.

**Comment by secure-77** [comment]
Good news, this will be fixed in 1.5.2

**Comment by secure-77** [comment]
fixed in https://github.com/secure-77/Perlite/releases/tag/1.5.2
