### ISSUE TITLE
Environment Variables for Line Breaks and Other Styling

### ISSUE THREAD

**Issue by athshean** [secure-77/Perlite#34]
**Is your feature request related to a problem? Please describe.**

I wanted to enable strict line breaks in a Docker install of Perlite.

**Describe the solution you'd like**

It would be useful if there were environment variables we could use to change these behaviours instead of having to edit the php files.

**Describe alternatives you've considered**

Installed the Docker image to a local volume and used a text editor to change the files. This is an imperfect solution because it would be overwritten upon future updates. Environment variables would be a much better in the long run.

**Additional context**

**Comment by secure-77** [comment]
added in version / branch 1.5
