### ISSUE TITLE
Font Size Slider Not Behaving as Expected

### ISSUE THREAD

**Issue by athshean** [secure-77/Perlite#35]
**Describe the bug**
Branch `1.5_beta`

When changing the font size using the slider, the following behaviours happen:
- The starting position does not reflect the current or defaukt font size, but instead is exactly half way of the slider length.
- Moving the slider to the half way point (i.e. the default starting point) does not reset the font to the default size, but is instead a larger size.
- Clicking the reset font size button does not move the slider back to the default position.

**To Reproduce**
1. Clean install of Perlite
2. Changing the font size in either the global Settings panel or the individual page settings

**Expected behavior**
- Font slider starting position would reflect current font size
- Moving the slider back to the default position should reset to the default font size

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Chrome
 - Version 106.0.5249.119 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: iPhone11 Pro Max
 - OS: iOS 16
 - Browser Safari

**Additional context**
Discussed on Discord

**Comment by secure-77** [comment]
fixed in https://github.com/secure-77/Perlite/commit/fea6ac7d4a2dbbb121365062922c826f85c9a939
