### ISSUE TITLE
Responsiveness of Sidebars Not Working Properly When Enlarging Window

### ISSUE THREAD

**Issue by athshean** [secure-77/Perlite#36]
**Describe the bug**
When the browser window width <= 990 px, the responsive layout hides the right-hand sidebar and makes the left hand sidebar collapsible, minimising it to a menu button when a page is opened. When the left hand sidebar has been collapsed and the browser then scales up above the 990 px breakpoint, then the menu button is hidden but the menu itself is not shown.

Furthermore, when the menu is expanded, it squeezes the main content panel. It would look a lot better if the main content panel was hidden when the menu was toggled open.

Also, if the browser width is  <= ca 1050 px, the right hand sidebar overlaps over the button to minimise the sidebar, making it impossible to close that sidebar and focus on the main content. Perhaps it would be useful to set a minimum width for the main content panel so that it does not get squeezed by the sidebars in a way that prevents the buttons from being operable?

**To Reproduce**
1. View a page on a browser with width less than 990 px
2. Open a page so that the page content is visible but the menu is collapsed
3. Scale the browser width above 990 px

**Expected behavior**
The menu button should be hidden when the browser width is > 990px, but the menu should also be shown.
The main content panel should have a minimum width so that the buttons to hide the right hand sidebar do not get covered by the sidebar.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Chrome

**Smartphone (please complete the following information):**
 - Device: [e.g. iPad Pro 11" 2021]
 - OS: iOS 15.5
 - Browser Safari

**Additional Context**
Screenshots in Discord

**Comment by secure-77** [comment]
fixed in https://github.com/secure-77/Perlite/commit/fea6ac7d4a2dbbb121365062922c826f85c9a939
