### ISSUE TITLE
Make Graph View Toggleable via Left Sidebar

### ISSUE THREAD

**Issue by athshean** [secure-77/Perlite#37]
**Is your feature request related to a problem? Please describe.**
If Graph View is enabled, then the only way to close Graph View is by clicking on the 'x' button. Clicking the Graph View button again or navigating to a different file in the vault do not close Graph View. In Obsidian, you can exit Graph View by navigating to a file.

**Describe the solution you'd like**
Making the Graph View button toggleable so clicking it again would close the Graph View. Navigating to a different page from within Graph View would also close Graph View.
This would be a much more intuitive UX.

**Comment by secure-77** [comment]
added in https://github.com/secure-77/Perlite/commit/fea6ac7d4a2dbbb121365062922c826f85c9a939
