### ISSUE TITLE
Regression: callouts render as regular block quotes

### ISSUE THREAD

**Issue by Tooa** [secure-77/Perlite#40]
**Describe the bug**

Obsidian [callouts](https://help.obsidian.md/How+to/Use+callouts) render as regular block quotes after the upgrade to Perite 1.5. This is a regression issue since the feature was being introduced in #26 ([original feature request](https://github.com/secure-77/Perlite/issues/20)).

**To Reproduce**

1. Go to `https://perlite.secure77.de/?link=%2FDemo%20Documents%2Fmarkdown-sample3`
4. Observe regular block quote styling rather than callout formatting

**Expected behavior**

- Callouts render at least with accent color depending on their type
- Optional: Callouts render with their dedicated icon
- Optional: Callouts can be folded

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox 106.0.2 (64-bit)

**Comment by Kerato-san** [comment]
Looking at the css, the function still works but it's not defined in the css. With a proper css theme it should look correct.

**Comment by secure-77** [comment]
Unfortunately it is not so easy to rebuild the div structure we need to match with obsidian themes. 

@Tooa if you have some time I would appreciate your help for extending the parsedown function

**Comment by secure-77** [comment]
I have created an issue on parsedown, hopfully find some help there:

https://github.com/erusev/parsedown/issues/843

**Comment by secure-77** [comment]
finally figured out how to support this, was a lot of work and I need to overwrite several default functions of parsedown to support nested elements in blocks but now it should work as expected.

![image](https://user-images.githubusercontent.com/31564517/205244237-3aebfed6-eb0e-45ac-a4ad-5bc85faa89ff.png)


will be in the next 1.5.1 release
