### ISSUE TITLE
block  support 

### ISSUE THREAD

**Issue by LeiYanhua** [secure-77/Perlite#41]
huge thanks to secure-77 and all other contributors!

I would like to suggest  block / heading transcluding or embedding  as is follows:
[[ source md]]  ;   [[source md# heading | alias]] ;   [[[[source md#^ block | alias]]
and 
with ! before [[ , for embedding

To materailize  the above suggested feature,   https://github.com/ppeetteerrs/obsidian-zola/compare/main...rockmanvnx6:obsidian-zola:preview-popup   may be helpful

**Comment by LeiYanhua** [comment]
For anyone who may be interested in developing the suggested feature, 
https://github.com/ppeetteerrs/obsidian-zola/commit/c77055ddf8e2ee07e54d270225adb6590590d458

**Comment by secure-77** [comment]
Hi @LeiYanhua 
I was thinking about to implement some kind of modal / mouse hover function, showing content from other markdown files.
Check: https://github.com/secure-77/Perlite/issues/43
But at the moment I can´t say if this will then also support pointing to a specific block / header section (If I understand your request correct).

So for the moment I will first take a look at Issue 43.

**Comment by secure-77** [comment]
Please take a look at #43, at the moment I don`t think I will implement the header preview reference.
