### ISSUE TITLE
first line break not considered

### ISSUE THREAD

**Issue by ZephyrOff** [secure-77/Perlite#46]
I just noticed that in a note, the first line break is not converted to an html line break. 
For example, in my headers, on obsidian I have one line per field, and on perlite everything is on the same line.

![image](https://user-images.githubusercontent.com/55457378/206686193-144ef17e-d7ca-45db-8bba-dade61ed6955.png)
![image](https://user-images.githubusercontent.com/55457378/206686231-3682514a-9bba-47f0-b472-91d90a9f5a1f.png)

**Comment by secure-77** [comment]
I can`t reproduce this, can you please provide the source code of your .md file

**Comment by secure-77** [comment]
please take the latest release, should be fixed now

**Comment by ZephyrOff** [comment]
Thanks for the fast patch
