### ISSUE TITLE
The symbol ( & ) in note names is replaced by ( &amp ) which breaks the graph links

### ISSUE THREAD

**Issue by SmartSceptic** [secure-77/Perlite#47]
**Describe the bug**

I use special characters in the name of notes in my knowledge base to determine the type of note.
At least, symbol ( & ) in note names is replaced by ( &amp ) on graph panel, with breaks the graph links, an lead to unexistent note.
When you go to such a note from the left panel, the graph is not updated, and when you go from the graph to such a note, a blank page opens.

Probably other special characters allowed in Windows for use in file names also lead to a similar error.

**To Reproduce**
- Create note, with name beginning wit "&"
- Try open note from graf view
- Try open note from left tree panel

**Expected behavior**
The symbol ( & ) and other windows allowed symbols in note names is not changed in view.

**Screenshots**
My test few notes in graf  (multiple node connections also look weird)
![image](https://user-images.githubusercontent.com/13509733/209925728-03c3a1f8-1854-43bf-b76e-7ebaab87e974.png)

![image](https://user-images.githubusercontent.com/13509733/209928360-48aa8ed7-b58c-4a34-82be-b567d1009b96.png)

**Desktop (please complete the following information):**
 - OS: Windows  11
 - Browser Google Chrom
 - Version Latest perlite 1.5.1

**Comment by secure-77** [comment]
I can reproduce this, seems that the html encoding should be replaced to url encoding for the links

**Comment by secure-77** [comment]
Well this will be fixed in release 1.5.2, but only for the ampersand, it seems that the json parser from php will decode some chars which then I need to replace back with JS, which is pretty ugly and need to be done for every (wrong escaped) char.

But at least the ampersand is fixed and I know what to do if there are more chars.

**Comment by secure-77** [comment]
fixed in https://github.com/secure-77/Perlite/releases/tag/1.5.2

**Comment by secure-77** [comment]
now also fixed for the global graph in 1.5.5
