### ISSUE TITLE
Checkboxes in tables with <input type='checkbox' />

### ISSUE THREAD

**Issue by Waayway** [secure-77/Perlite#48]
I am using this for DnD and  need  checkmarks in a table. i found this sort of stupid way by using html and now thats how i do it everywhere.
These checkmarks don't get rendered properly and just get displayed as text which is not correct.

I dont know how i would fix this since in obsidian you cannot use simple [ ] and [ x ] syntax

**Comment by neexa** [comment]
Same issue if you use :

\<mark> my important text \</mark> **witch does not render correctly**
or
\<span>\&#11088;\&#11088;\&#11088;\</span> witch sould show 3 stars <span>&#11088;&#11088;&#11088;</span>

**Comment by neexa** [comment]
Thank you !
 `$Parsedown->setSafeMode(false);` is working 👍 

 I still have problems showing Special Characters in HTML. It may be because of & sign

<span>&#11088;&#11088;&#11088;</span> witch sould show 3 stars ⭐⭐⭐
