### ISSUE TITLE
Having issues with Docker

### ISSUE THREAD

**Issue by rmccullagh99** [secure-77/Perlite#49]
Hi, I really like what this project is attempting to do, and have been trying to set it up using docker.
Unfortunately, it looks like the perlite_web container isn't available on dockerhub anymore, so the example docker-compose doesn't work.
Don't know if this is a docker-compose versioning thing or something, but my docker-compose errors out on the 'volumes_from' arg in the docker-compose.yml, and says to use volumes and share the vol's between containers.

Any help getting this set-up would be much appreciated!

**Comment by athshean** [comment]
Heya!

If I’m not mistaken, the perlite_web image is one you’ll need to build yourself. It’s fairly simple, just pull the Dockerfile from the repo and build it locally. It’s basically just an Nginx image that has the relevant configs copied in and mounted.

**Comment by Danny-mtb** [comment]
Hey, 

at the beginning we had the same problem we were able to solve it by installing the latest docker-compose version. which docker-compose version do you have installed?

**Comment by rmccullagh99** [comment]
Thanks guys! I'll have a look at building the image and see how I go.
docker-compose version 1.28.4, build cabd5cfb
Docker version 20.10.21, build baeda1f

**Comment by Danny-mtb** [comment]
Can you try to update the docker-compose version? I installed version 1.29.2 and it worked with that.

**Comment by rmccullagh99** [comment]
Thanks guys! Upgraded the docker-compose executable to 1.29.2 and tried with docker-compose CLI, which worked. Funnily enough even after upgrading the docker UI I've been using (Portainer) just wouldn't let it work.

Thanks both!
