### ISSUE TITLE
Three questions in README.md & New "helper.php"

### ISSUE THREAD

**Issue by Darkluna999** [secure-77/Perlite#5]
1. In README.md the line 92
[![coverage](https://img.shields.io/badge/vis.js-9.1.0-yellow)](https://https://visjs.org//)
it should be：
[![coverage](https://img.shields.io/badge/vis.js-9.1.0-yellow)](https://visjs.org//)

2. And when I use the new "helper.php" you provided me yesterday, the "about" button fails.
3. At present, it is not possible to support LaTex language input formulas, and I hope to add related functions

**Comment by secure-77** [comment]
Thanks for the Issue!

i fixed both in the latest commit, please try again the about modal. should be fine now

BR,
Sec77

**Comment by secure-77** [comment]
Because this is not trivial and i need to check if there is a easy way to support this, i outsources this latex topic to a new issue and close this one.
