### ISSUE TITLE
Password protect access

### ISSUE THREAD

**Issue by ArneNostitz** [secure-77/Perlite#52]
Hi, don't know if this is the right place to ask as I guess it's a webserver running thing more than a perlite issue, but is it somehow possible to restrict access to the web viewer? I want to run a team wiki, but not have this publicly accessable through the web. So some kind of login/ access control would be great. 

Sadly my understanding of "server stuff" is quite limited. And while it is madness, i do have a dedicated server and a hosted one to be used for this (would prefer the hosted option though) 

Thanks for any help or hint to the right ressources, cheers

**Comment by secure-77** [comment]
Hi @ArneNostitz,

At the moment this is only possible via the webserver but should not be hard to setup this if you go with a simple basic authentication. I just created an FAQ entry for this with some links, hopefully these help you!

https://github.com/secure-77/Perlite/wiki/FAQs#can-i-password-protect-perlite
