### ISSUE TITLE
Links to notes in another folder don't generate the correct URL.

### ISSUE THREAD

**Issue by VinnyTheLegend** [secure-77/Perlite#57]
**Describe the bug**
Auto generated links do not properly generate URLs for MD files in different folders. You end up with a URL that has the same folder as whatever file contained the link, with the target file in the URL. For example I click a link in a file inside the "apps" folder and the target is "samba" inside the "linux" folder but the URL ends up like this: ?link=%2Fapps%2Fsamba

**To Reproduce**
1. Add a link to a MD file in another folder.
2. Click on the link in the perlite web page
3. See the blank note page and notice the incorrect folder in the URL.

**Expected behavior**
The link should take you to the folder of the target file, not the folder containing the link.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Comment by secure-77** [comment]
https://github.com/secure-77/Perlite/wiki/03---Perlite-Settings#required-obsidian-settings

**Comment by VinnyTheLegend** [comment]
> 

I have done this of course.

**Comment by secure-77** [comment]
Then please provide the source code and an example of your folder structure.
Thanks

**Comment by VinnyTheLegend** [comment]
trying to make a link in data/apps/nextcloud.md that links to data/linux/samba.md

This actually seems to work fine:
[[../linux/samba]]  

But I cannot change the text of the link while keeping the link functional:
[samba](../linux/samba)
this translates to '/linux/samba' in the URL but the working URL would be '/?link=%2Flinux%2Fsamba'

**Comment by secure-77** [comment]
Yes, markdown links need a absolute URL and you should only use them for external links in Perlite.

If you are using the obsidian links format you need to use this `[[../linux/samba|samba]]`, this should work then also in Perlite.

See also: https://help.obsidian.md/Linking+notes+and+files/Internal+links#Change+the+link+display+text

**Comment by VinnyTheLegend** [comment]
Thank you, that works perfectly on both the client and Perlite. Appreciate such a quick reply. Apologies for opening up an issue for something simple like this.

**Comment by secure-77** [comment]
No problem! you are welcome!  glad you figured it out 😃
