### ISSUE TITLE
Support LaTeX

### ISSUE THREAD

**Issue by secure-77** [secure-77/Perlite#6]
Obsidian itself support latex, it seems that parsedown doesn´t, 

need to check if there is way or php latex parser to support this.

maybe this one: https://github.com/BenjaminHoegh/ParsedownMath

_Originally posted by @Darkluna999 in https://github.com/secure-77/Perlite/issues/5#issuecomment-1055684079_

**Comment by secure-77** [comment]
Not a fan of adding more dependencies but this looks promising:

![image](https://user-images.githubusercontent.com/31564517/156258584-a8cfc739-7ebc-49c2-a7e0-115eb74a1ed5.png)

**Comment by Darkluna999** [comment]
wow，yes，it is a wonderful enhancement

**Comment by secure-77** [comment]
Hi @Darkluna999 
i figured out that i only need to add the KaTeX dependencies to get this working, so i think i will release this later today or tomorrow.

**Comment by secure-77** [comment]
@Darkluna999 please take a look at the latest release 1.4.1 where LaTeX support is implemented.

BR,
Sec77

**Comment by Darkluna999** [comment]
OK，I'll try it later
