### ISSUE TITLE
hide commented out blocks

### ISSUE THREAD

**Issue by knikhil695** [secure-77/Perlite#60]
commented out (I keep it hide yaml from note metadata but for stuff like navigation, clean up) doesn't work on perlite

<img width="487" alt="Screenshot 2023-02-18 at 11 55 15 AM" src="https://user-images.githubusercontent.com/84435819/219845216-c78b3ad8-acb9-41ea-80ac-391e8ff074c9.png">

**Describe the solution you'd like**

It should like obsidian

<img width="822" alt="Screenshot 2023-02-18 at 12 01 15 PM" src="https://user-images.githubusercontent.com/84435819/219845227-85bf0b02-3a7b-41e7-9290-2941682c6f9b.png">

<img width="772" alt="Screenshot 2023-02-18 at 12 01 21 PM" src="https://user-images.githubusercontent.com/84435819/219845233-76b06902-5fe9-4035-af3e-936d1053eb40.png">

**Comment by secure-77** [comment]
[Obsidian Metadata](https://help.obsidian.md/Editing+and+formatting/Metadata) (front matter) is using yaml syntax, I cant find anything about using `%%` as a comment indicator. Yaml only supports `#` for commenting as far as I know.

also in your third screenshot (I suggest this shows obsidian) there is no front matter at all, so I suggest this is the obsidian view mode and you don`t have enabled the display of metadata. In Perlite you can also hide the metadata by clicking on the header or just hide it by default by changing this setting

![image](https://user-images.githubusercontent.com/31564517/222293039-75ba458b-e326-4a2b-a68d-fca5a6f804a9.png)
