### ISSUE TITLE
mouseleave Bug

### ISSUE THREAD

**Issue by blackwhite084** [secure-77/Perlite#62]
![image](https://user-images.githubusercontent.com/53146034/220270987-b91d8e88-73f7-4ad2-b512-26cd6d9b536a.png)

If the mouse moves over multiple links continuously, this function will trigger multiple timers, causing the newly opened pop-up window to be closed by the previous timer

**Comment by blackwhite084** [comment]
mayby can write stopThis = true on $('.internal-link').mouseenter(function (e)

**Comment by secure-77** [comment]
can confirm this, but not sure if the effort is it worth to fix this, it was already a pain to implement it as it is at the moment. 
best way to use this feature is to hover over the link and then move the mouse into the popover window, then it will stay open until you leave it.
