### ISSUE TITLE
Request for docker arm64

### ISSUE THREAD

**Issue by phampyk** [secure-77/Perlite#65]
I just tried to build perlite on my raspberry pi running arm64 raspiOS and it's completely compatible with it, could it be possible to have it compiled in arm64 from github/dockerhub? 
Thank you for the app, looks great, just what I was looking for.

**Comment by secure-77** [comment]
Hey @phampyk 
Unfortunately I have no arm64 environment here and I also don´t want to setup an emulator and testing this. The repository also contains the [Dockerfile](https://github.com/secure-77/Perlite/blob/main/perlite/Dockerfile) of the perlite image, so you can try to build your own image. Let me know if you get this running then we can add this to the wiki and repo.

**Comment by phampyk** [comment]
Yes, I am running it right now on my raspberry pi 4, built from the dockerfile, with no issues. So it's fully compatible

**Comment by secure-77** [comment]
What are the changes you made in the docker file? Can we create a separate docker and compose file for this ? You can also create a PR if you want

**Comment by phampyk** [comment]
I didn't do any changes, the basefiles you use are multi arch already so I only needed to build in my raspberry pi and it worked, nothing different at all.

**Comment by secure-77** [comment]
ah ok, but then I think I can't provide a pre build arm64 image and the best way is to build it on the target environment you are using

**Comment by phampyk** [comment]
You can build multiarch when pushing to dockerhub without having to own that environment yourself. There's one [here](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/) explaining how. 
That way I, and anyone who wants to use it, can pull it from dockerhub every time you update or fix bugs.
And I already tested that works on arm64 so should be easy to do.
Hope this helps! I think it would be helpful to have it multi arch so more people can benefit from perlite even if it's on a raspberry pi :)

**Comment by secure-77** [comment]
ok thanks 👍  I will take a look at this as soon I have some time

**Comment by catrone3** [comment]
This actually looks like it would be quite easy to setup with a github workflow, although if you are manually creating the images still not that bad

**Comment by secure-77** [comment]
implemented from version 1.5.7, there will be also always a docker image for arm. thanks to @knorr3
