### ISSUE TITLE
Folders doesn’t expand

### ISSUE THREAD

**Issue by ramisedhom** [secure-77/Perlite#7]
**Describe the bug**
I tried Perlite on my local machine, move my vault to `root`, add perlite code there and it opens, Viola, it’s magic!! :slight_smile:

However, folders doesn’t expand, when I click on folder, I got this error in browser console:
```
Uncaught DOMException: Document.querySelector: '#1.-Projects-collapse' is not a valid selector
    i index.js:64
    <anonymous> collapse.js:318
    n event-handler.js:119
```

**To Reproduce**
1. Downloaded PAAN Starter Kit from: https://forum.obsidian.md/t/paan-starter-kit/21782
2. Expanded into my apache root folder (I tried also with nginx), named the folder as `paan`
3. Added Perlite code there in same folder
4. Opened browser to http://localhost:8080/paan
5. Site is working for files outside folders but folders doesn't expand

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome and firefox

**Comment by secure-77** [comment]
Hi @ramisedhom,

i can reproduce it, there are actually two issues which javascript does not link in a html id
- the folder must not contain a dot
- the folder must not start with a number

i fixed this already, just working on a new release, think today or latest tomorrow i will release it.

BR and thanks for the report!

**Comment by secure-77** [comment]
@ramisedhom please take a look a the latest release 1.4.1 and let me know if the problem is fixed.

Thank you and BR,
Sec77

**Comment by ramisedhom** [comment]
It's fixed, thanks for fast responses 👍🏻
