### ISSUE TITLE
<font></font> tag support

### ISSUE THREAD

**Issue by zy55769068** [secure-77/Perlite#71]
I have many notes that contain content such as `<font color="sky blue">mature</font>`, but they are displayed as plain text on the web.

<img width="281" alt="image" src="https://user-images.githubusercontent.com/29294137/229417929-c3e6b708-4216-419c-9d1a-f9801bebf076.png">

Is there any solution to support this feature?

**Comment by secure-77** [comment]
You need to disable the safemode for this: https://github.com/secure-77/Perlite/wiki/FAQs#can-i-use-plain-html-in-perlite

**Comment by zy55769068** [comment]
Thank you, I apologize for missing this.
