### ISSUE TITLE
Support same document heading links

### ISSUE THREAD

**Issue by lennartbrandin** [secure-77/Perlite#74]
# Feature / Issue
Obsidian supports same document heading references using Wiki Links
```
[[#Solution]] 
```
Instead having the word "Solution" linking to `https://perlite/?link=/github/issues/samedoclinks#Solution`

It displays `">#Solution` (The `">` being the link and the `#Solution` a codeblock) linking to:
`https://perlite/?link=/github/issues/<a href="#Solution`

# Solution
Display the correct word linking to the correct heading

# Whats displayed

![image](https://user-images.githubusercontent.com/92579517/231567314-73d7eab7-dd29-4e5c-91d7-b02c7e6c0edb.png)

**Comment by secure-77** [comment]
fixed in release [1.5.4](https://github.com/secure-77/Perlite/releases/tag/1.5.4)

**Comment by secure-77** [comment]
Need to check this again and provide an example in the demo files

**Comment by secure-77** [comment]
(hopefully) finally fixed in 1.5.5

**Comment by lennartbrandin** [comment]
It does not seem to work for me on 1.5.5
Behavior is as described before, i've also noticed that links inside code blocks are replaced, not sure if this is intended.

Perlite:
![image](https://github.com/secure-77/Perlite/assets/92579517/2fb93386-70d6-4b69-aae6-4861e61568d1)

Obsidian:
![image](https://github.com/secure-77/Perlite/assets/92579517/902cc083-f325-4de4-842c-b3c589ae6a33)

**Comment by secure-77** [comment]
for me, this is working, you can take a look at the demo page: https://perlite.secure77.de/?link=%2FDemo%20Documents%2Fmarkdown-sample

![image](https://github.com/secure-77/Perlite/assets/31564517/a67a8697-b7f5-4caf-ba68-ac5c26a8843e)

![image](https://github.com/secure-77/Perlite/assets/31564517/6f4cd6e4-2031-427c-9620-5e941f65a31b)

however, can you provide me your source md file?

the problem with obsidian links in code blocks is probably a different issue

**Comment by lennartbrandin** [comment]
https://perlite.lennartbrandin.com/
[Source.md](https://github.com/secure-77/Perlite/files/11612198/Source.md)

**Comment by lennartbrandin** [comment]
![image](https://github.com/secure-77/Perlite/assets/92579517/90df9e1e-ca05-4a18-bf66-a03fcbeeca2e)
The first link is now as imagined, the 2nd one links to the root of the containing folder. (\[\[\#Test|Mit Title\]\])

**Comment by secure-77** [comment]
this is implemented on the dev branche, will merge it in the next days to main

**Comment by secure-77** [comment]
fixed in 1.5.7
