### ISSUE TITLE
Support KaTex in headings

### ISSUE THREAD

**Issue by lennartbrandin** [secure-77/Perlite#78]
## The Problem with KaTex in headings
When trying to use KaTeX $$ inside of headings, two things should be different:
- The heading is no longer inside the Table of Contents
- Links to those headings are picked up by the Parsedown and converted as usual

**Describe the solution you'd like**
List those headings in the TOC.
Dont replace KaTex used inside of links

**Additional context**
Link being replaced:
![image](https://user-images.githubusercontent.com/92579517/235206300-c02cd258-93ed-4f57-ad2e-dfa20b6b82e4.png)

**Comment by secure-77** [comment]
handling different languages and styles (markdown, katex, html) in one heading or link can be very complex and time consuming and as this seems to be a edge case for me, I think I won't find time to take care about this at the moment, sorry.
