### ISSUE TITLE
Support for Dataviews

### ISSUE THREAD

**Issue by hobojoe720** [secure-77/Perlite#81]
Dataviews is a heavily used plugin for Obsidian and I am not even sure if its possible for Perlite to integrate with Dataviews.

However this would be a very big enhancement if it could be implemented. Since the entire Vault is included, access to the dataviews main.js and styles.css are possible

**Comment by secure-77** [comment]
Sorry, but supporting plugins is currently not planned, there are to many and it's to much work to implement, track and maintain changes from plugins
