### ISSUE TITLE
Is Gitlab Flavored Markdown (GLFM) supported?

### ISSUE THREAD

**Issue by Keonik1** [secure-77/Perlite#83]
Is there any formatting support that is used in GLFM? I would like to publish documentation written in GLFM based on your project.
https://docs.gitlab.com/ee/user/markdown.html

**Comment by secure-77** [comment]
Unfortunately no, some markdown from GLFM may work but I haven't tested this and its not planed to integrate such support. Perlite is mainly for supporting Obsidian related Markdown

**Comment by Keonik1** [comment]
@secure-77 thanks for answer!
