### ISSUE TITLE
Default column widths

### ISSUE THREAD

**Issue by NotGovernor** [secure-77/Perlite#85]
**Is your feature request related to a problem? Please describe.**
When the site comes up for a new person for the first time, the left and right columns take up an overly large percentage of space on desktop browsers.

**Describe the solution you'd like**
Minimally, we should set the defaults to something that focuses on the content pane in the center. Ideally, the default percentages would be a setting accessible to admins in an environment variable in the docker-compose file.

Current default view:
https://imgur.com/a/3bqcMSh

Suggested:
https://imgur.com/a/RExsx0B

**Comment by secure-77** [comment]
Ah I see, this seems to be a problem on smaller resolution screens, at wqhd the relation is ok.

![image](https://github.com/secure-77/Perlite/assets/31564517/b298c1ee-0c73-4f0b-9726-4a317eb3f4ab)

Adjusting the panel sizes based on the windows size is good idea 👍

**Comment by NotGovernor** [comment]
You might want to implement something more dynamic for differing ratios and resolutions -- but heres a temp fix (maybe?). Feel free to reject if you'd like. No worries.

https://github.com/secure-77/Perlite/pull/87

**Comment by secure-77** [comment]
implemented in 1.5.6
