### ISSUE TITLE
Image links to external URLS dont work

### ISSUE THREAD

**Issue by NotGovernor** [secure-77/Perlite#89]
**Describe the bug**
Image links to external URLS dont work.

**To Reproduce**
Craft a link like the following that wraps a local image with an external URL.

```
[![[files/Image.jpg]]](https://website.com)
```

**Expected behavior**
The image is linked.

**Actual**
The image is rendered but the link url is placed outside with the square brackets visible.

**Comment by secure-77** [comment]
I'm not sure if this is really a bug or not but embedding external images is working fine if you specify the full path in the link section and don't split it.

Example, this is working

`![Minion](https://octodex.github.com/images/minion.png)`

Also I can't see any advantage of splitting the image link so I won't fix this.

**Comment by NotGovernor** [comment]
This bug might have been misunderstood. The goal is to show an image (local or remote doesnt matter) that when clicked opens an external URL.

From my example `![[files/Image.jpg]]` is the image. In this case a local one, but that's not the problem being raised. It's when you then wrap that in another link as in the OP example that it is rendered improperly.

Sorry for my report not being clear enough. Hope this helps. :)

**Comment by secure-77** [comment]
Ah ok, got it, I will reopen this issue as a feature request

**Comment by secure-77** [comment]
implemented in release [1.5.9](https://github.com/secure-77/Perlite/releases/tag/1.5.9)

**Comment by NotGovernor** [comment]
Just pure unmitigated awesome. Thank you sir.
