### ISSUE TITLE
support footnotes

### ISSUE THREAD

**Issue by secure-77** [secure-77/Perlite#9]
Footnotes are some "extra" Markdown feature, to support this with the current parser I`m using (parsedown), I would need to add [parsedown-extra](https://github.com/erusev/parsedown-extra)

unfortunately there is an issue with footnotes and enabled safeMode: https://github.com/erusev/parsedown-extra/issues/158

![image](https://user-images.githubusercontent.com/31564517/157112927-5a8311cc-694f-4e64-ad43-e9c9047cb09a.png)

without the safeMode it is working fine
![image](https://user-images.githubusercontent.com/31564517/157113007-f3d89c29-3965-4ba1-860f-e25cebd04f2a.png)

However, at the moment I wont implement this at the cost of losing safeMode, so I need to wait for fix in parsedown-extra or need to look for a different markedown parser.

**Comment by Darkluna999** [comment]
Good! Hope your development goes well
