### ISSUE TITLE
Graph control button is not visible on mobile screen size

### ISSUE THREAD

**Issue by Physicys** [secure-77/Perlite#91]
I can barely tap the setting/control button and when it open I can't close it since the `X` is not visible too, this happened to small viewport device.
I'm not sure if I should put this under enhancement or bug report but I think it's better to add support for smaller screen size

![Screen Shot 2023-06-01 at 01 08 00](https://github.com/secure-77/Perlite/assets/116349837/db272a98-f7f7-4185-9dc0-d53af4e52617)

![Screen Shot 2023-06-01 at 01 09 11](https://github.com/secure-77/Perlite/assets/116349837/3c58ee8c-a506-4089-a0ad-460b5a53e832)

**Comment by Physicys** [comment]
in dev tools it's Samsung S10 and S20, I think a screen with a width of less than 390px can't show the button properly, my phone screen size is 360px x 728px

![image](https://github.com/secure-77/Perlite/assets/116349837/7966a2cf-8fde-4a40-b395-f5d95f4aa9b2)

**Comment by secure-77** [comment]
This seems to be firefox related issue, in chrome I have no issues with this, I will try to fix it

**Comment by secure-77** [comment]
fixed in 1.5.7
