### ISSUE TITLE
Work with Custom CSS from Themes

### ISSUE THREAD

**Issue by Nargath** [secure-77/Perlite#98]
**Is your feature request related to a problem? Please describe.**
When using a theme that has custom css snippets embedded in the theme's code, those aren't rendering, or working as intended on the Perlite hosted site.
For example, I'm building a info repository using the ITS theme (https://github.com/SlRvb/Obsidian--ITS-Theme), which has a slew of custom CSS in it that enhances what the core callouts are and can do.
Introduces wiki-style infoboxes, collapsible callouts, being able to manipulate the look and make up of callouts.
But these only render the basic Obsidian callouts, and most of the time jumble the page.

**Describe the solution you'd like**
To see Perlite be able to handle custom css snippets that may be embedded in other Theme's direct code.

**Additional context**

First screenshot is the callouts working correctly in Obsidian.
The infobox on the right hand side, and the coloured and bordered boxes are new types of callouts, as well as being marked as collapsible, and having the icon removed as part of the code.
![ITS Callouts Example - Obsidian](https://github.com/secure-77/Perlite/assets/5538979/d8f6ee58-d4f9-40b0-badf-c98a70f7e9f0)

This is that exact same page as rendered in Perlite, noting that the infobox on the right is now inside a standard callout, and the collapsible callouts underneath are fully expanded and don't even have the option for collapsing.
![ITS Callouts Example - Perlite](https://github.com/secure-77/Perlite/assets/5538979/17001905-d95b-423f-88c9-4b2e994e6db2)

**Comment by Nargath** [comment]
I've had a small break through with this.

It isn't that the css snippets themselves aren't working; its the attributes that are associated with the custom css code.

Callouts are adjustable via attributes within the initial callout code. They are separated from the main callout component by a pipe |
So a normal "metadata" callout is:
[!metadata]

To have a collapsible metadata callout needs to be:
[!metadata]+

And to have a metadata callout with the title, or the title icon needs to be:
[!metadata|no-t no-i]

When I have callouts with attributes in Perlite, it breaks them rendering as the custom callouts, and reverts them back to Obsidian internal callouts, namely the default Info one.

Here's a screenshot of Perlite with a infobox and metadata callout without attributes, and then a metadata with attributes underneath the line
![image](https://github.com/secure-77/Perlite/assets/5538979/b52774a5-d247-42d8-be1b-f5dcce81631e)

**Comment by secure-77** [comment]
I can see the problem but to implement different html structures or obsidian tag handles based on theme seems very complex and a never ending story. I didn't`t think I can take care about this. Its already a lot of work to handle the default obsidian functionalities. 
So best what you can do is to fork the project and adjust it by yourself I guess...

**Comment by Nargath** [comment]
Yeah, I figured it might be well beyond scope of the app, but figured it didn't hurt to bring it up!

And I'd fork it and make the changes myself, but honestly I'd be so completely lost, I wouldn't even know where to start :P

**Comment by Nargath** [comment]
Yeah, I figured it might be well beyond scope of the app, but figured it didn't hurt to bring it up!

And I'd fork it and make the changes myself, but honestly I'd be so completely lost, I wouldn't even know where to start :P
